app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Tomato
publisher_url: https://github.com/hiddify/hiddify-next
display_name: Tomato
executable_name: Tomato.exe
output_base_file_name: Tomato.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\Tomato"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
script_template: inno_setup.sas
